[package]
name = "infrastructure"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
domain = { path = "../domain" }
use-cases = { path = "../use-cases" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
chrono.workspace = true
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "sqlite", "migrate"] }
async-trait.workspace = true
kamadak-exif = "0.6"
image = "0.24"
rawloader = "0.37.1"

[dev-dependencies]
tempfile.workspace = true
mockall.workspace = true
