[package]
name = "use-cases"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
domain = { path = "../domain" }
thiserror.workspace = true
serde.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
chrono.workspace = true
rayon.workspace = true
futures.workspace = true
sha2 = "0.10"

[dev-dependencies]
mockall.workspace = true
proptest.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "test-util"] }
