//! O rótulo de cada ajuste, na ordem do painel do site.
//!
//! É a `TODOS_OS_CONTROLES` de `revelacao/ajustes.ts`, campo e rótulo, gerada
//! de lá em 17/set/2026. Existe para o **resumo** das predefinições — "Guarda 3
//! ajustes: Exposição, Contraste, Sombras." —, que no site sai desta lista e
//! nesta ordem: os módulos do darktable primeiro, depois Básico, Curva de tons,
//! Curva por ponto, HSL, Preto e branco, Detalhe, Lente, Calibração,
//! Tonalização e Efeitos.
//!
//! ⚠️ **Não é a lista de controles desta coluna da direita** (`controles.rs`),
//! que tem outra ordem e outro dono. O resumo é texto de tela, e para ele sair
//! igual nas duas plataformas a fonte tem de ser a do site. Os rótulos do HSL são
//! só o nome da cor — "Laranja, Laranja" num preset que mexe em saturação e
//! luminância do laranja —, como lá.
//!
//! O teste abaixo prende que cada um dos ajustes do motor tem rótulo, e só eles.

/// `(campo, rótulo)`, na ordem de `TODOS_OS_CONTROLES`.
pub const ROTULOS: &[(&str, &str)] = &[
    ("dt_exposure_ativo", "Ligar"),
    ("dt_exposure_exposure", "Exposição (EV)"),
    ("dt_exposure_black", "Correção do nível de preto"),
    ("dt_shadhi_ativo", "Ligar"),
    ("dt_shadhi_shadows", "Sombras"),
    ("dt_shadhi_highlights", "Realces"),
    ("dt_shadhi_whitepoint", "Ajuste do ponto branco"),
    ("dt_shadhi_radius", "Raio (px da foto original)"),
    ("dt_shadhi_compress", "Compressão"),
    ("dt_shadhi_shadows_ccorrect", "Cor das sombras"),
    ("dt_shadhi_highlights_ccorrect", "Cor dos realces"),
    ("dt_shadhi_flags", "Limites (flags UNBOUND)"),
    ("dt_monochrome_ativo", "Ligar"),
    ("dt_monochrome_a", "Filtro — a (verde ↔ magenta)"),
    ("dt_monochrome_b", "Filtro — b (azul ↔ amarelo)"),
    ("dt_monochrome_size", "Largura do filtro"),
    ("dt_monochrome_highlights", "Preservar realces"),
    ("dt_vignette_ativo", "Ligar"),
    ("dt_vignette_scale", "Início da queda (%)"),
    ("dt_vignette_falloff_scale", "Raio da queda (%)"),
    ("dt_vignette_brightness", "Brilho"),
    ("dt_vignette_saturation", "Saturação"),
    ("dt_vignette_center_x", "Centro — horizontal"),
    ("dt_vignette_center_y", "Centro — vertical"),
    ("dt_vignette_autoratio", "Proporção automática"),
    ("dt_vignette_whratio", "Proporção largura/altura"),
    ("dt_vignette_shape", "Forma"),
    ("dt_vignette_unbound", "Sem recorte de valores"),
    ("dt_cb_ativo", "Ligar"),
    ("dt_cb_shadows_y", "Sombras — luminância"),
    ("dt_cb_shadows_c", "Sombras — croma"),
    ("dt_cb_shadows_h", "Sombras — matiz"),
    ("dt_cb_midtones_y", "Meios-tons — luminância"),
    ("dt_cb_midtones_c", "Meios-tons — croma"),
    ("dt_cb_midtones_h", "Meios-tons — matiz"),
    ("dt_cb_highlights_y", "Realces — luminância"),
    ("dt_cb_highlights_c", "Realces — croma"),
    ("dt_cb_highlights_h", "Realces — matiz"),
    ("dt_cb_global_y", "Global — luminância"),
    ("dt_cb_global_c", "Global — croma"),
    ("dt_cb_global_h", "Global — matiz"),
    ("dt_cb_hue_angle", "Deslocamento de matiz"),
    ("dt_cb_vibrance", "Vibração global"),
    ("dt_cb_contrast", "Contraste"),
    ("dt_cb_chroma_global", "Croma — global"),
    ("dt_cb_chroma_shadows", "Croma — sombras"),
    ("dt_cb_chroma_midtones", "Croma — meios-tons"),
    ("dt_cb_chroma_highlights", "Croma — realces"),
    ("dt_cb_saturation_global", "Saturação — global"),
    ("dt_cb_saturation_shadows", "Saturação — sombras"),
    ("dt_cb_saturation_midtones", "Saturação — meios-tons"),
    ("dt_cb_saturation_highlights", "Saturação — realces"),
    ("dt_cb_brilliance_global", "Brilho — global"),
    ("dt_cb_brilliance_shadows", "Brilho — sombras"),
    ("dt_cb_brilliance_midtones", "Brilho — meios-tons"),
    ("dt_cb_brilliance_highlights", "Brilho — realces"),
    ("dt_cb_shadows_weight", "Máscara — queda das sombras"),
    ("dt_cb_highlights_weight", "Máscara — queda dos realces"),
    ("dt_cb_white_fulcrum", "Máscara — fulcro branco (EV)"),
    ("dt_cb_mask_grey_fulcrum", "Máscara — fulcro cinza"),
    ("dt_cb_grey_fulcrum", "Fulcro cinza do contraste"),
    ("exposure", "Exposição"),
    ("contrast", "Contraste"),
    ("temperature", "Temperatura"),
    ("tint", "Matiz"),
    ("highlights", "Altas luzes"),
    ("shadows", "Sombras"),
    ("whites", "Brancos"),
    ("blacks", "Pretos"),
    ("clarity", "Textura"),
    ("vibrance", "Intensidade"),
    ("saturation", "Saturação"),
    ("tone_curve_shadows", "Sombras"),
    ("tone_curve_darks", "Escuros"),
    ("tone_curve_lights", "Claros"),
    ("tone_curve_highlights", "Altas luzes"),
    ("curva_m0", "RGB — ponto 1"),
    ("curva_m1", "RGB — ponto 2"),
    ("curva_m2", "RGB — ponto 3"),
    ("curva_m3", "RGB — ponto 4"),
    ("curva_m4", "RGB — ponto 5"),
    ("curva_m5", "RGB — ponto 6"),
    ("curva_m6", "RGB — ponto 7"),
    ("curva_m7", "RGB — ponto 8"),
    ("curva_m8", "RGB — ponto 9"),
    ("curva_r0", "Vermelho — ponto 1"),
    ("curva_r1", "Vermelho — ponto 2"),
    ("curva_r2", "Vermelho — ponto 3"),
    ("curva_r3", "Vermelho — ponto 4"),
    ("curva_r4", "Vermelho — ponto 5"),
    ("curva_r5", "Vermelho — ponto 6"),
    ("curva_r6", "Vermelho — ponto 7"),
    ("curva_r7", "Vermelho — ponto 8"),
    ("curva_r8", "Vermelho — ponto 9"),
    ("curva_g0", "Verde — ponto 1"),
    ("curva_g1", "Verde — ponto 2"),
    ("curva_g2", "Verde — ponto 3"),
    ("curva_g3", "Verde — ponto 4"),
    ("curva_g4", "Verde — ponto 5"),
    ("curva_g5", "Verde — ponto 6"),
    ("curva_g6", "Verde — ponto 7"),
    ("curva_g7", "Verde — ponto 8"),
    ("curva_g8", "Verde — ponto 9"),
    ("curva_b0", "Azul — ponto 1"),
    ("curva_b1", "Azul — ponto 2"),
    ("curva_b2", "Azul — ponto 3"),
    ("curva_b3", "Azul — ponto 4"),
    ("curva_b4", "Azul — ponto 5"),
    ("curva_b5", "Azul — ponto 6"),
    ("curva_b6", "Azul — ponto 7"),
    ("curva_b7", "Azul — ponto 8"),
    ("curva_b8", "Azul — ponto 9"),
    ("hsl_red_sat", "Vermelho"),
    ("hsl_orange_sat", "Laranja"),
    ("hsl_yellow_sat", "Amarelo"),
    ("hsl_green_sat", "Verde"),
    ("hsl_aqua_sat", "Água"),
    ("hsl_blue_sat", "Azul"),
    ("hsl_purple_sat", "Roxo"),
    ("hsl_magenta_sat", "Magenta"),
    ("hsl_red_lum", "Vermelho"),
    ("hsl_orange_lum", "Laranja"),
    ("hsl_yellow_lum", "Amarelo"),
    ("hsl_green_lum", "Verde"),
    ("hsl_aqua_lum", "Água"),
    ("hsl_blue_lum", "Azul"),
    ("hsl_purple_lum", "Roxo"),
    ("hsl_magenta_lum", "Magenta"),
    ("hsl_red_hue", "Vermelho"),
    ("hsl_orange_hue", "Laranja"),
    ("hsl_yellow_hue", "Amarelo"),
    ("hsl_green_hue", "Verde"),
    ("hsl_aqua_hue", "Água"),
    ("hsl_blue_hue", "Azul"),
    ("hsl_purple_hue", "Roxo"),
    ("hsl_magenta_hue", "Magenta"),
    ("bw_ativo", "Converter para P&B"),
    ("bw_red", "Vermelhos"),
    ("bw_orange", "Laranjas"),
    ("bw_yellow", "Amarelos"),
    ("bw_green", "Verdes"),
    ("bw_aqua", "Águas"),
    ("bw_blue", "Azuis"),
    ("bw_purple", "Roxos"),
    ("bw_magenta", "Magentas"),
    ("nr_luminance", "Ruído (luminância)"),
    ("nr_color", "Ruído (cor)"),
    ("sharpen_amount", "Nitidez"),
    ("sharpen_radius", "Raio da nitidez"),
    ("lens_distortion", "Distorção"),
    ("lens_vignette_amount", "Vinheta"),
    ("lens_vignette_midpoint", "Meio da vinheta"),
    ("calib_shadow_tint", "Sombras — matiz"),
    ("calib_red_hue", "Vermelho — matiz"),
    ("calib_red_sat", "Vermelho — saturação"),
    ("calib_green_hue", "Verde — matiz"),
    ("calib_green_sat", "Verde — saturação"),
    ("calib_blue_hue", "Azul — matiz"),
    ("calib_blue_sat", "Azul — saturação"),
    ("split_shadow_hue", "Sombras — matiz"),
    ("split_shadow_sat", "Sombras — saturação"),
    ("split_midtone_hue", "Tons médios — matiz"),
    ("split_midtone_sat", "Tons médios — saturação"),
    ("split_highlight_hue", "Altas luzes — matiz"),
    ("split_highlight_sat", "Altas luzes — saturação"),
    ("split_global_hue", "Global — matiz"),
    ("split_global_sat", "Global — saturação"),
    ("split_balance", "Balanço"),
    ("split_blending", "Mistura"),
    ("grain_amount", "Grão"),
    ("grain_size", "Tamanho do grão"),
];

#[cfg(test)]
mod testes {
    use std::collections::HashSet;

    use super::*;
    use crate::revelacao::processador::Ajustes;

    /// 🔑 **Um rótulo por ajuste do motor, e nenhum a mais.** Um campo novo no
    /// shader sem linha aqui apareceria no resumo com o nome em inglês.
    #[test]
    fn cada_ajuste_do_motor_tem_um_rotulo() {
        let da_tabela: HashSet<&str> = ROTULOS.iter().map(|(campo, _)| *campo).collect();
        let do_motor: HashSet<&str> = Ajustes::NOMES.iter().copied().collect();
        assert_eq!(ROTULOS.len(), da_tabela.len(), "campo repetido na tabela");
        assert_eq!(da_tabela, do_motor);
    }
}
