[package]
name = "ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
egui = "0.31"
eframe = { version = "0.31", default-features = false, features = [
    "default_fonts",
    "wgpu",
    "persistence",
    "accesskit"
]}
egui_extras = { version = "0.31", features = ["image"] }
egui-notify = "0.19"
poll-promise = "0.3"
tokio.workspace = true
rfd = { version = "0.14.1", features = ["file-handle-inner"] }
infrastructure = { path = "../infrastructure" }
adapters = { path = "../adapters" }
use-cases = { path = "../use-cases" }
domain = { path = "../domain" }
image = "0.24"
rayon = "1.10"
parking_lot = "0.12"
wgpu = "23.0"
bytemuck = { version = "1.14", features = ["derive"] }
pollster = "0.4"
lru = "0.16.2"
dotenv = "0.15.0"


[dev-dependencies]
egui_kittest = { version = "0.31", features = ["wgpu", "snapshot"] }
