#!/usr/bin/env python3
"""Regressoes do instalador, sem rede, compilacao ou instalacao de dependencias.

Execute: python3 scripts/testar-instalador.py
PowerShell e validado se pwsh estiver disponivel; cmd.exe exige Windows real.
"""

import io
import os
from pathlib import Path
import shutil
import subprocess
import tarfile
import tempfile
import unittest


SCRIPT = Path(__file__).with_name("instalar-vintagelightbox.cmd").resolve()


class Instalador(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix="vlb-teste-")
        self.addCleanup(self.temp.cleanup)
        self.base = Path(self.temp.name)
        self.bin = self.base / "bin"
        self.bin.mkdir()
        self.casa = self.base / "cache"
        self.fonte = self.casa / "fonte-tauri"
        self.destino = self.base / "Aplicativos"
        self.home = self.base / "home"
        self.home.mkdir()
        self.log = self.base / "cargo.log"
        self.archive = self.base / "fonte.tar.gz"
        self.env = dict(os.environ, HOME=str(self.home), VLB_CASA=str(self.casa),
                        PATH=f"{self.bin}:/usr/bin:/bin:/usr/sbin:/sbin",
                        TEST_ARCHIVE=str(self.archive), TEST_LOG=str(self.log),
                        LIBCLANG_PATH=str(self.bin))
        (self.bin / "libclang.so").touch()
        self.mock("uname", "echo Darwin")
        self.mock("xcrun", "echo /usr/bin/clang++")
        self.mock("xcode-select", "echo /Developer")
        self.mock("rustc", "echo 'rustc 1.98.0 (teste)'")
        self.mock("pkg-config", "echo 4.1")
        self.mock("codesign", "exit 0")
        self.mock("ditto", 'cp -R "$1" "$2"')
        self.mock("curl", '''
while [ "$#" -gt 0 ]; do
  if [ "$1" = -o ]; then cp "$TEST_ARCHIVE" "$2"; break; fi
  shift
done
exit "${TEST_CURL_EXIT:-0}"
''')
        self.mock("cargo", '''
printf '%s\\n' "$*" >> "$TEST_LOG"
[ "${TEST_BUILD_EXIT:-0}" -eq 0 ] || exit "$TEST_BUILD_EXIT"
mkdir -p "$CARGO_TARGET_DIR/release"
printf '#!/bin/sh\\nexit 0\\n' > "$CARGO_TARGET_DIR/release/app-tauri"
chmod +x "$CARGO_TARGET_DIR/release/app-tauri"
fonte="$VLB_CASA/fonte-tauri"
mkdir -p "$fonte/crates/app-tauri/gen" "$fonte/crates/app-tauri/permissions/autogenerated"
echo gerado > "$fonte/crates/app-tauri/gen/schema.json"
echo gerado > "$fonte/crates/app-tauri/permissions/autogenerated/comando.toml"
[ -f "$fonte/Cargo.lock" ] || echo '# lock local' > "$fonte/Cargo.lock"
''')
        self.files = {
            "Cargo.toml": '[workspace.package]\nversion = "0.1.8"\n',
            "Cargo.lock": "# lock de teste\n",
            "crates/app-tauri/Cargo.toml": '[package]\nname = "app-tauri"\n',
            "empacotamento/icones/icone.icns": "icone",
            "empacotamento/icones/256x256.png": "icone",
        }
        self.archive_files()

    def mock(self, name, body):
        file = self.bin / name
        file.write_text("#!/bin/sh\nset -eu\n" + body + "\n")
        file.chmod(0o755)

    def archive_files(self):
        with tarfile.open(self.archive, "w:gz") as archive:
            for name, content in self.files.items():
                data = content.encode()
                info = tarfile.TarInfo("repo/" + name)
                info.size = len(data)
                archive.addfile(info, io.BytesIO(data))

    def run_installer(self, *args, piped=False):
        command = ["/bin/sh", "-s", "--"] if piped else ["/bin/sh", str(SCRIPT)]
        return subprocess.run(
            command + ["--destino", str(self.destino), *args], env=self.env,
            input=SCRIPT.read_text() if piped else None, text=True,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=20,
        )

    def old_source(self):
        self.fonte.mkdir(parents=True)
        (self.fonte / "anterior").write_text("preservar")

    def assert_preserved(self, result):
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertEqual((self.fonte / "anterior").read_text(), "preservar")
        self.assertFalse(self.log.exists())
        self.assertEqual(list(self.casa.glob("download.*")), [])

    def test_download_com_erro_mesmo_com_arquivo_completo(self):
        self.old_source()
        self.env["TEST_CURL_EXIT"] = "18"
        self.assert_preserved(self.run_installer())

    def test_arquivo_corrompido(self):
        self.old_source()
        self.archive.write_text("incompleto")
        self.assert_preserved(self.run_installer())

    def test_versao_sem_app(self):
        self.old_source()
        del self.files["crates/app-tauri/Cargo.toml"]
        self.archive_files()
        self.assert_preserved(self.run_installer())

    def test_versao_sem_lock_preserva_resolucao_local(self):
        del self.files["Cargo.lock"]
        self.archive_files()
        first = self.run_installer()
        self.assertEqual(first.returncode, 0, first.stdout)
        lock = self.fonte / "Cargo.lock"
        lock.write_text("# resolucao local anterior")
        second = self.run_installer()
        self.assertEqual(second.returncode, 0, second.stdout)
        self.assertEqual(lock.read_text(), "# resolucao local anterior")
        self.assertIn("código sem alterações", second.stdout)

    def test_reinstalacao_preserva_datas_com_arquivos_gerados(self):
        first = self.run_installer(piped=True)
        self.assertEqual(first.returncode, 0, first.stdout)
        manifest = self.fonte / "Cargo.toml"
        os.utime(manifest, (1234567890, 1234567890))
        second = self.run_installer()
        self.assertEqual(second.returncode, 0, second.stdout)
        self.assertEqual(manifest.stat().st_mtime, 1234567890)
        self.assertTrue((self.destino / "VintageLightbox (Tauri).app/Contents/MacOS/app-tauri").exists())
        self.assertEqual(list(self.casa.glob("download.*")), [])

    def test_codigo_alterado_e_substituido(self):
        self.old_source()
        result = self.run_installer()
        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertFalse((self.fonte / "anterior").exists())
        self.assertEqual((self.fonte / "Cargo.toml").read_text(), self.files["Cargo.toml"])

    def test_build_falha_preserva_app_instalado(self):
        app = self.destino / "VintageLightbox (Tauri).app"
        app.mkdir(parents=True)
        (app / "anterior").write_text("preservar")
        self.env["TEST_BUILD_EXIT"] = "42"
        result = self.run_installer()
        self.assertEqual(result.returncode, 42, result.stdout)
        self.assertEqual((app / "anterior").read_text(), "preservar")

    def test_seco_nao_grava(self):
        result = self.run_installer("--seco")
        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertFalse(self.casa.exists())
        self.assertFalse(self.destino.exists())
        self.assertFalse(self.log.exists())

    def test_linux_instala_binario_e_atalho(self):
        self.mock("uname", "echo Linux")
        result = self.run_installer(piped=True)
        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertTrue((self.destino / "bin/vintagelightbox-tauri").exists())
        self.assertTrue((self.destino / "share/applications/vintagelightbox-tauri.desktop").exists())

    @unittest.skipUnless(shutil.which("pwsh"), "PowerShell indisponivel")
    def test_powershell_sintaxe_e_falha_nativa(self):
        # Analise o bloco real e execute sua funcao Correr com executaveis reais.
        harness = self.base / "conferir.ps1"
        harness.write_text(r'''
$ErrorActionPreference = 'Stop'
$texto = [IO.File]::ReadAllText($args[0])
$inicio = $texto.IndexOf("`n#==POWERSHELL==")
$fim = $texto.IndexOf("`n#==FIM-POWERSHELL==", $inicio)
$tokens = $null; $erros = $null
$ast = [System.Management.Automation.Language.Parser]::ParseInput(
    $texto.Substring($inicio, $fim - $inicio), [ref]$tokens, [ref]$erros)
if ($erros.Count) { throw ($erros | Out-String) }
$funcao = $ast.Find({ param($n)
    $n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq 'Correr'
}, $true)
Invoke-Expression $funcao.Extent.Text
$Seco = $false
$falhou = $false
try { Correr { & /bin/sh -c 'exit 23' } } catch { $falhou = $_ -match 'codigo 23' }
if (-not $falhou) { throw 'engoliu erro nativo' }
Correr { & /bin/sh -c 'exit 0' }
$Seco = $true
Correr { throw 'modo seco executou o comando' }
foreach ($nome in 'Assinatura-Fonte', 'Tem-WebView2') {
    $funcao = $ast.Find({ param($n)
        $n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $n.Name -eq $nome
    }, $true)
    Invoke-Expression $funcao.Extent.Text
}
$pasta = Join-Path $PSScriptRoot 'fonte'
New-Item -ItemType Directory -Path "$pasta/crates/app-tauri/gen" -Force | Out-Null
Set-Content "$pasta/Cargo.toml" 'original'
$antes = @(Assinatura-Fonte $pasta)
Set-Content "$pasta/crates/app-tauri/gen/schema.json" 'gerado'
$depois = @(Assinatura-Fonte $pasta)
if (Compare-Object $antes $depois) { throw 'arquivo gerado invalidou cache' }
Set-Content "$pasta/Cargo.toml" 'alterado'
if (-not (Compare-Object $antes @(Assinatura-Fonte $pasta))) { throw 'ignorou fonte alterada' }
$chaves = @('maquina', 'usuario')
function Get-ItemProperty { param($LiteralPath, $Name, $ErrorAction)
    if ($LiteralPath -eq 'usuario') { [pscustomobject]@{ pv = $script:pvTeste } }
}
foreach ($pvTeste in $null, '', '0.0.0.0', 'invalido') {
    if (Tem-WebView2) { throw 'aceitou WebView2 ausente' }
}
$pvTeste = '140.0.1.0'
if (-not (Tem-WebView2)) { throw 'nao detectou WebView2 por usuario' }
''')
        result = subprocess.run([shutil.which("pwsh"), "-NoProfile", "-File", str(harness), str(SCRIPT)],
                                capture_output=True, text=True, timeout=20)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)


if __name__ == "__main__":
    unittest.main(verbosity=2)
