[package]
name = "domain"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
uuid.workspace = true
chrono.workspace = true
async-trait.workspace = true
serde_json.workspace = true

[dev-dependencies]
proptest.workspace = true
fake.workspace = true
serde_json.workspace = true
